on: [push]

name: Deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --release --all-features
      - run: echo ${{GH_PAT | docker login ghcr.io -u clanny --password-stdin
        env:
          GH_PAT: ${{ secrets.GH_SECRET }}
        name: Login to GH container registry
      -
        name: Build Docker image and push it
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/clanny/group_addition_agent:latest