on: [push, workflow_dispatch]

name: Deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: echo $GH_PAT | docker login ghcr.io -u clanny --password-stdin
        env:
          GH_PAT: ${{ secrets.GH_SECRET }}
        name: Login to GH container registry

      - run: docker build . --tag ghcr.io/clanny/group_addition_agent:latest
      - run: docker push ghcr.io/clanny/group_addition_agent:latest